name: Build Specification

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull texlive image
        run: |
          docker pull texlive/texlive

      - name: Compile JDF Document
        run: |
          docker run --rm -i -v $(pwd):/workdir texlive/texlive pdflatex -jobname=jdf-specification <<EOF
            \newcommand\gitsha{${{ github.sha }}}
            \input{jdf-specification.tex}
          EOF

      - name: Compile XJDF Document
        run: |
          docker run --rm -i -v $(pwd):/workdir texlive/texlive pdflatex -jobname=xjdf-specification <<EOF
            \newcommand\gitsha{${{ github.sha }}}
            \input{jdf-specification.tex}
          EOF

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            ./jdf-specification.pdf
            ./xjdf-specification.pdf
