name: Build Specification

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull texlive image
        run: |
          docker pull texlive/texlive

      - name: Compile JDF Document
        run: |
          cat <<EOF > build-jdf.tex
            \newcommand\type{JDF}
            \newcommand\version{1.9}
            \newcommand\gitsha{${{ github.sha }}}
            \input{main.tex}
          EOF
          docker run --rm -i -v $(pwd):/workdir texlive/texlive latexmk -pdflua -jobname=jdf-specification build-jdf.tex

      - name: Compile XJDF Document
        run: |
          cat <<EOF > build-xjdf.tex
            \newcommand\type{XJDF}
            \newcommand\version{2.3}
            \newcommand\gitsha{${{ github.sha }}}
            \input{main.tex}
          EOF
          docker run --rm -i -v $(pwd):/workdir texlive/texlive latexmk -pdflua -jobname=xjdf-specification build-xjdf.tex

      - name: Compile BOTH Document
        run: |
          cat <<EOF > build-both.tex
            \newcommand\type{BOTH}
            \newcommand\version{1.9+2.3}
            \newcommand\gitsha{${{ github.sha }}}
            \input{main.tex}
          EOF
          docker run --rm -i -v $(pwd):/workdir texlive/texlive latexmk -pdflua -jobname=both-specification build-both.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            ./jdf-specification.pdf
            ./jdf-specification.log
            ./xjdf-specification.pdf
            ./xjdf-specification.log
            ./both-specification.pdf
            ./both-specification.log
