name: Build Specification

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile TEX Document
        run: |
          docker run --rm -v $(pwd):/workdir texlive/texlive lualatex jdf-specification.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: jdf-specification.pdf

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: jdf-specification.log